### ISSUE TITLE
do we really need to login to use instaloader?

### ISSUE THREAD

**Issue by codeblech** [codeblech/jpgram-cdn#4]

**Comment by codelif** [comment]
No, I was going to add cmdline option to remove that. 

But it make things easier for my network.

**Comment by codeblech** [comment]
did instagram ~cock~block reqs without login?

**Comment by codelif** [comment]
> did instagram ~cock~block reqs without login?

yes it did. for me atleast

**Comment by codeblech** [comment]
let's at least have an option to run without login. that sounds good?

**Comment by codelif** [comment]
yes.
